-- Create Bytebase admin user with full permissions
CREATE USER bytebase WITH PASSWORD 'bytebase123' SUPERUSER CREATEDB CREATEROLE LOGIN;

-- Grant all privileges on database
GRANT ALL PRIVILEGES ON DATABASE car_recsys TO bytebase;

-- Connect to car_recsys database and grant schema permissions
\c car_recsys

-- Grant usage and create on schemas
GRANT USAGE, CREATE ON SCHEMA raw TO bytebase;
GRANT USAGE, CREATE ON SCHEMA silver TO bytebase;
GRANT USAGE, CREATE ON SCHEMA gold TO bytebase;
GRANT USAGE, CREATE ON SCHEMA public TO bytebase;

-- Grant all privileges on all tables in schemas
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA raw TO bytebase;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA silver TO bytebase;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA gold TO bytebase;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO bytebase;

-- Grant all privileges on all sequences in schemas
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA raw TO bytebase;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA silver TO bytebase;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA gold TO bytebase;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO bytebase;

-- Set default privileges for future objects
ALTER DEFAULT PRIVILEGES IN SCHEMA raw GRANT ALL ON TABLES TO bytebase;
ALTER DEFAULT PRIVILEGES IN SCHEMA silver GRANT ALL ON TABLES TO bytebase;
ALTER DEFAULT PRIVILEGES IN SCHEMA gold GRANT ALL ON TABLES TO bytebase;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO bytebase;

ALTER DEFAULT PRIVILEGES IN SCHEMA raw GRANT ALL ON SEQUENCES TO bytebase;
ALTER DEFAULT PRIVILEGES IN SCHEMA silver GRANT ALL ON SEQUENCES TO bytebase;
ALTER DEFAULT PRIVILEGES IN SCHEMA gold GRANT ALL ON SEQUENCES TO bytebase;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO bytebase;

-- Create admin user for general use (optional)
CREATE USER admin_user WITH PASSWORD 'admin_pass123';
GRANT ALL PRIVILEGES ON DATABASE car_recsys TO admin_user;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA raw, silver, gold, public TO admin_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA raw, silver, gold, public TO admin_user;
ALTER DEFAULT PRIVILEGES GRANT ALL ON TABLES TO admin_user;
ALTER DEFAULT PRIVILEGES GRANT ALL ON SEQUENCES TO admin_user;
